import envConfig from "../config/route.config";
import { auth } from "../lib/auth";
import { prisma } from "../lib/prisma";


async function upsertUser(
  name: string,
  email: string,
  password: string,
  role: string,
  inviteCode?: string
) {
  const existing = await prisma.user.findUnique({ where: { email } });
  if (existing) {
    await prisma.user.update({ where: { email }, data: { role: role as any } });
    return existing;
  }

  const res = await auth.api.signUpEmail({
    body: { name, email, password },
    headers: new Headers({
      "x-intended-role": role,
      ...(inviteCode ? { "x-staff-invite-code": inviteCode } : {}),
    }),
  });
console.log("===============> ", res);
  const user = await prisma.user.findUniqueOrThrow({ where: { email } });
  // Force role — needed because Google-OAuth users skip the hook
  await prisma.user.update({ where: { id: user.id }, data: { role: role as any } });
  return user;
}

function dec(n: number) {
  return n; // Prisma accepts plain numbers for Decimal fields
}

// ─────────────────────────────────────────────────────────────────────────────

async function main() {
  console.log("🌱 Seeding MediTrack…");

  // ── 1. Users ────────────────────────────────────────────────────────────────
  console.log("  → Users");

  const adminUser = await upsertUser(envConfig.ADMIN_Name, envConfig.ADMIN_Email, envConfig.ADMIN_Password, "ADMIN");
  const pharmacyUser = await upsertUser(envConfig.PHARMACY_Name, envConfig.PHARMACY_Email, envConfig.PHARMACY_Password, "PHARMACY");
  const userUser = await upsertUser(envConfig.USER_Name, envConfig.USER_Email, envConfig.USER_Password, "USER");
  // Staff is created after pharmacy so we have the invite code
  // We'll wire it manually below

  // ── 2. Catalogue ────────────────────────────────────────────────────────────
  console.log("  → Catalogue (categories, types, units, leaf settings, suppliers)");

  const [catAntibiotics, catAnalgesics, catAntivirals, catVitamins, catCardio, catGastro] =
    await Promise.all([
      prisma.category.upsert({ where: { slug: "antibiotics" }, update: {}, create: { name: "Antibiotics", slug: "antibiotics", description: "Drugs that kill or inhibit bacterial growth" } }),
      prisma.category.upsert({ where: { slug: "analgesics" }, update: {}, create: { name: "Analgesics", slug: "analgesics", description: "Pain relieving medications" } }),
      prisma.category.upsert({ where: { slug: "antivirals" }, update: {}, create: { name: "Antivirals", slug: "antivirals", description: "Medications that inhibit viral replication" } }),
      prisma.category.upsert({ where: { slug: "vitamins" }, update: {}, create: { name: "Vitamins & Minerals", slug: "vitamins", description: "Nutritional supplements" } }),
      prisma.category.upsert({ where: { slug: "cardiovascular" }, update: {}, create: { name: "Cardiovascular", slug: "cardiovascular", description: "Heart and blood pressure medications" } }),
      prisma.category.upsert({ where: { slug: "gastroenterology" }, update: {}, create: { name: "Gastroenterology", slug: "gastroenterology", description: "Digestive system medications" } }),
    ]);

  const [typeTablet, typeCapsule, typeSyrup, typeInjection, typeOintment] =
    await Promise.all([
      prisma.medicineType.upsert({ where: { name: "Tablet" }, update: {}, create: { name: "Tablet", description: "Solid oral dosage form" } }),
      prisma.medicineType.upsert({ where: { name: "Capsule" }, update: {}, create: { name: "Capsule", description: "Gelatin shell encapsulating medication" } }),
      prisma.medicineType.upsert({ where: { name: "Syrup" }, update: {}, create: { name: "Syrup", description: "Liquid oral dosage form" } }),
      prisma.medicineType.upsert({ where: { name: "Injection" }, update: {}, create: { name: "Injection", description: "Parenteral dosage form" } }),
      prisma.medicineType.upsert({ where: { name: "Ointment" }, update: {}, create: { name: "Ointment", description: "Topical semi-solid preparation" } }),
    ]);

  const [unitMg, unitMl, unitPcs, unitGm] = await Promise.all([
    prisma.unit.upsert({ where: { name: "Milligram" }, update: {}, create: { name: "Milligram", symbol: "mg" } }),
    prisma.unit.upsert({ where: { name: "Millilitre" }, update: {}, create: { name: "Millilitre", symbol: "ml" } }),
    prisma.unit.upsert({ where: { name: "Piece" }, update: {}, create: { name: "Piece", symbol: "pcs" } }),
    prisma.unit.upsert({ where: { name: "Gram" }, update: {}, create: { name: "Gram", symbol: "gm" } }),
  ]);

  const leafStd = await prisma.leafSetting.upsert({
    where: { name: "Standard 10×10" },
    update: {},
    create: { name: "Standard 10×10", leavesPerStrip: 10, stripsPerBox: 10, description: "10 tablets per strip, 10 strips per box" },
  });

  const [supSquare, supOrion, supBeximco] = await Promise.all([
    prisma.supplier.upsert({ where: { email: "square@pharma.com" }, update: {}, create: { name: "Square Pharmaceuticals", contactPerson: "Md. Rafiq", email: "square@pharma.com", phone: "01700000001", address: "Dhaka, Bangladesh" } }),
    prisma.supplier.upsert({ where: { email: "orion@pharma.com" }, update: {}, create: { name: "Orion Pharma", contactPerson: "Ms. Nadia", email: "orion@pharma.com", phone: "01700000002", address: "Chittagong, Bangladesh" } }),
    prisma.supplier.upsert({ where: { email: "beximco@pharma.com" }, update: {}, create: { name: "Beximco Pharma", contactPerson: "Mr. Hasan", email: "beximco@pharma.com", phone: "01700000003", address: "Gazipur, Bangladesh" } }),
  ]);

  // ── 3. Medicines ─────────────────────────────────────────────────────────────
  console.log("  → Medicines");

  const medicineData = [
    {
      name: "Amoxicillin",
      genericName: "Amoxicillin Trihydrate",
      strength: "500mg",
      boxSize: "10x10",
      shelf: "A1",
      price: 12.5,
      supplierPrice: 9,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 500,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Common antibiotic medicine used for bacterial infections.",
      categoryId: catAntibiotics.id,
      typeId: typeTablet.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Paracetamol",
      genericName: "Acetaminophen",
      strength: "500mg",
      boxSize: "10x10",
      shelf: "A2",
      price: 5,
      supplierPrice: 3.5,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 1000,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Pain and fever relief medicine commonly used in Bangladesh.",
      categoryId: catAnalgesics.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Napa Syrup",
      genericName: "Paracetamol",
      strength: "120mg/5ml",
      boxSize: "1 bottle",
      shelf: "B1",
      price: 35,
      supplierPrice: 25,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 200,
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Paracetamol syrup for fever and pain relief.",
      categoryId: catAnalgesics.id,
      typeId: typeSyrup.id,
      supplierId: supOrion.id,
      unitId: unitMl.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Azithromycin",
      genericName: "Azithromycin",
      strength: "250mg",
      boxSize: "1x6",
      shelf: "A3",
      price: 45,
      supplierPrice: 30,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 300,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Macrolide antibiotic used for selected bacterial infections.",
      categoryId: catAntibiotics.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Oseltamivir",
      genericName: "Oseltamivir Phosphate",
      strength: "75mg",
      boxSize: "1x10",
      shelf: "C1",
      price: 120,
      supplierPrice: 90,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 150,
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Antiviral capsule used for influenza treatment support.",
      categoryId: catAntivirals.id,
      typeId: typeCapsule.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Vitamin C",
      genericName: "Ascorbic Acid",
      strength: "500mg",
      boxSize: "10x10",
      shelf: "D1",
      price: 8,
      supplierPrice: 5,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 800,
      image: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Vitamin supplement used for immune and nutritional support.",
      categoryId: catVitamins.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Atorvastatin",
      genericName: "Atorvastatin Calcium",
      strength: "10mg",
      boxSize: "10x10",
      shelf: "E1",
      price: 18,
      supplierPrice: 12,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 400,
      image: "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Cholesterol-lowering medicine used in cardiovascular care.",
      categoryId: catCardio.id,
      typeId: typeTablet.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Omeprazole",
      genericName: "Omeprazole",
      strength: "20mg",
      boxSize: "10x10",
      shelf: "F1",
      price: 10,
      supplierPrice: 7,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 600,
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Capsule used for acidity, reflux, and gastric care.",
      categoryId: catGastro.id,
      typeId: typeCapsule.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Metronidazole",
      genericName: "Metronidazole",
      strength: "400mg",
      boxSize: "10x10",
      shelf: "A4",
      price: 7.5,
      supplierPrice: 5,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 350,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Antibacterial and antiprotozoal medicine.",
      categoryId: catAntibiotics.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Ibuprofen",
      genericName: "Ibuprofen",
      strength: "400mg",
      boxSize: "10x10",
      shelf: "A5",
      price: 9,
      supplierPrice: 6,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 700,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Pain relief and anti-inflammatory tablet.",
      categoryId: catAnalgesics.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Metformin",
      genericName: "Metformin HCl",
      strength: "500mg",
      boxSize: "10x10",
      shelf: "E2",
      price: 6,
      supplierPrice: 4,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 900,
      image: "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Common diabetes medicine for blood sugar control.",
      categoryId: catCardio.id,
      typeId: typeTablet.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Cetirizine",
      genericName: "Cetirizine HCl",
      strength: "10mg",
      boxSize: "10x10",
      shelf: "A6",
      price: 4.5,
      supplierPrice: 3,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 500,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Antihistamine tablet used for allergy symptoms.",
      categoryId: catAnalgesics.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },

    {
      name: "Cefixime",
      genericName: "Cefixime Trihydrate",
      strength: "200mg",
      boxSize: "1x10",
      shelf: "A7",
      price: 32,
      supplierPrice: 23,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 280,
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Cephalosporin antibiotic capsule used for selected bacterial infections.",
      categoryId: catAntibiotics.id,
      typeId: typeCapsule.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Ciprofloxacin",
      genericName: "Ciprofloxacin HCl",
      strength: "500mg",
      boxSize: "10x10",
      shelf: "A8",
      price: 14,
      supplierPrice: 10,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 420,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Antibiotic tablet used for bacterial infections.",
      categoryId: catAntibiotics.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Levofloxacin",
      genericName: "Levofloxacin Hemihydrate",
      strength: "500mg",
      boxSize: "10x10",
      shelf: "A9",
      price: 22,
      supplierPrice: 15,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 260,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Fluoroquinolone antibiotic tablet.",
      categoryId: catAntibiotics.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Doxycycline",
      genericName: "Doxycycline Hyclate",
      strength: "100mg",
      boxSize: "10x10",
      shelf: "A10",
      price: 6.5,
      supplierPrice: 4.5,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 380,
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Antibiotic capsule used for selected bacterial infections.",
      categoryId: catAntibiotics.id,
      typeId: typeCapsule.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Flucloxacillin",
      genericName: "Flucloxacillin Sodium",
      strength: "500mg",
      boxSize: "10x10",
      shelf: "A11",
      price: 15,
      supplierPrice: 11,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 240,
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Antibiotic capsule used for bacterial infection treatment.",
      categoryId: catAntibiotics.id,
      typeId: typeCapsule.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Clarithromycin",
      genericName: "Clarithromycin",
      strength: "500mg",
      boxSize: "1x10",
      shelf: "A12",
      price: 55,
      supplierPrice: 40,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 180,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Macrolide antibiotic tablet.",
      categoryId: catAntibiotics.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },

    {
      name: "Diclofenac",
      genericName: "Diclofenac Sodium",
      strength: "50mg",
      boxSize: "10x10",
      shelf: "B2",
      price: 4,
      supplierPrice: 2.8,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 850,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Pain relief and anti-inflammatory tablet.",
      categoryId: catAnalgesics.id,
      typeId: typeTablet.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Naproxen",
      genericName: "Naproxen Sodium",
      strength: "500mg",
      boxSize: "10x10",
      shelf: "B3",
      price: 12,
      supplierPrice: 8.5,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 360,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Pain relief and anti-inflammatory medicine.",
      categoryId: catAnalgesics.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Aspirin",
      genericName: "Acetylsalicylic Acid",
      strength: "75mg",
      boxSize: "10x10",
      shelf: "B4",
      price: 3,
      supplierPrice: 2,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 1100,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Low-dose aspirin used in cardiovascular support and pain relief.",
      categoryId: catAnalgesics.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Tramadol",
      genericName: "Tramadol HCl",
      strength: "50mg",
      boxSize: "10x10",
      shelf: "B5",
      price: 8,
      supplierPrice: 5.5,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 250,
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Pain relief capsule for moderate pain management.",
      categoryId: catAnalgesics.id,
      typeId: typeCapsule.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Aceclofenac",
      genericName: "Aceclofenac",
      strength: "100mg",
      boxSize: "10x10",
      shelf: "B6",
      price: 7,
      supplierPrice: 4.8,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 480,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Anti-inflammatory pain relief tablet.",
      categoryId: catAnalgesics.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Ketorolac",
      genericName: "Ketorolac Tromethamine",
      strength: "10mg",
      boxSize: "10x10",
      shelf: "B7",
      price: 6,
      supplierPrice: 4,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 320,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Pain relief tablet for short-term pain management.",
      categoryId: catAnalgesics.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },

    {
      name: "Acyclovir",
      genericName: "Acyclovir",
      strength: "400mg",
      boxSize: "10x10",
      shelf: "C2",
      price: 28,
      supplierPrice: 20,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 160,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Antiviral tablet used for herpes virus infections.",
      categoryId: catAntivirals.id,
      typeId: typeTablet.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Valacyclovir",
      genericName: "Valacyclovir HCl",
      strength: "500mg",
      boxSize: "1x10",
      shelf: "C3",
      price: 65,
      supplierPrice: 48,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 120,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Antiviral medicine used for selected viral infections.",
      categoryId: catAntivirals.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Favipiravir",
      genericName: "Favipiravir",
      strength: "200mg",
      boxSize: "10x10",
      shelf: "C4",
      price: 45,
      supplierPrice: 34,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 140,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Antiviral tablet used for selected viral treatment support.",
      categoryId: catAntivirals.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Ribavirin",
      genericName: "Ribavirin",
      strength: "200mg",
      boxSize: "10x10",
      shelf: "C5",
      price: 22,
      supplierPrice: 16,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 130,
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Antiviral capsule used for selected viral infections.",
      categoryId: catAntivirals.id,
      typeId: typeCapsule.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Lamivudine",
      genericName: "Lamivudine",
      strength: "100mg",
      boxSize: "10x10",
      shelf: "C6",
      price: 18,
      supplierPrice: 13,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 170,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Antiviral tablet used in long-term viral disease management.",
      categoryId: catAntivirals.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },

    {
      name: "Vitamin D3",
      genericName: "Cholecalciferol",
      strength: "2000IU",
      boxSize: "10x10",
      shelf: "D2",
      price: 10,
      supplierPrice: 7,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 750,
      image: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Vitamin D supplement used for nutritional support.",
      categoryId: catVitamins.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Vitamin B Complex",
      genericName: "B-Complex Vitamins",
      strength: "100mg",
      boxSize: "10x10",
      shelf: "D3",
      price: 6.5,
      supplierPrice: 4.5,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 900,
      image: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "B-complex vitamin supplement tablet.",
      categoryId: catVitamins.id,
      typeId: typeTablet.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Calcium D",
      genericName: "Calcium Carbonate + Vitamin D3",
      strength: "500mg",
      boxSize: "10x10",
      shelf: "D4",
      price: 9.5,
      supplierPrice: 6.8,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 650,
      image: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Calcium and Vitamin D supplement for bone health support.",
      categoryId: catVitamins.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Zinc",
      genericName: "Zinc Sulfate",
      strength: "20mg",
      boxSize: "10x10",
      shelf: "D5",
      price: 5,
      supplierPrice: 3.2,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 700,
      image: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Zinc supplement tablet for nutritional support.",
      categoryId: catVitamins.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Iron Folic",
      genericName: "Ferrous Sulfate + Folic Acid",
      strength: "200mg",
      boxSize: "10x10",
      shelf: "D6",
      price: 4.5,
      supplierPrice: 3,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 800,
      image: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Iron and folic acid supplement tablet.",
      categoryId: catVitamins.id,
      typeId: typeTablet.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Multivitamin Syrup",
      genericName: "Multivitamin Preparation",
      strength: "100ml",
      boxSize: "1 bottle",
      shelf: "D7",
      price: 85,
      supplierPrice: 62,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 180,
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Liquid multivitamin preparation for nutritional support.",
      categoryId: catVitamins.id,
      typeId: typeSyrup.id,
      supplierId: supBeximco.id,
      unitId: unitMl.id,
      leafSettingId: leafStd.id,
    },

    {
      name: "Amlodipine",
      genericName: "Amlodipine Besylate",
      strength: "5mg",
      boxSize: "10x10",
      shelf: "E3",
      price: 5,
      supplierPrice: 3.5,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 650,
      image: "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Blood pressure medicine used in cardiovascular care.",
      categoryId: catCardio.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Losartan",
      genericName: "Losartan Potassium",
      strength: "50mg",
      boxSize: "10x10",
      shelf: "E4",
      price: 8,
      supplierPrice: 5.8,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 580,
      image: "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Blood pressure medicine used in cardiovascular care.",
      categoryId: catCardio.id,
      typeId: typeTablet.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Bisoprolol",
      genericName: "Bisoprolol Fumarate",
      strength: "5mg",
      boxSize: "10x10",
      shelf: "E5",
      price: 7.5,
      supplierPrice: 5.2,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 420,
      image: "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Beta blocker tablet used in cardiovascular care.",
      categoryId: catCardio.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Rosuvastatin",
      genericName: "Rosuvastatin Calcium",
      strength: "10mg",
      boxSize: "10x10",
      shelf: "E6",
      price: 20,
      supplierPrice: 14,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 390,
      image: "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Cholesterol-lowering tablet used in cardiovascular care.",
      categoryId: catCardio.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Clopidogrel",
      genericName: "Clopidogrel Bisulfate",
      strength: "75mg",
      boxSize: "10x10",
      shelf: "E7",
      price: 12,
      supplierPrice: 8.5,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 450,
      image: "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Antiplatelet tablet used in cardiovascular care.",
      categoryId: catCardio.id,
      typeId: typeTablet.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Atenolol",
      genericName: "Atenolol",
      strength: "50mg",
      boxSize: "10x10",
      shelf: "E8",
      price: 4.5,
      supplierPrice: 3,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 500,
      image: "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Beta blocker tablet used in blood pressure management.",
      categoryId: catCardio.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Furosemide",
      genericName: "Furosemide",
      strength: "40mg",
      boxSize: "10x10",
      shelf: "E9",
      price: 3.5,
      supplierPrice: 2.5,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 460,
      image: "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Diuretic tablet used in cardiovascular and fluid management.",
      categoryId: catCardio.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Enalapril",
      genericName: "Enalapril Maleate",
      strength: "5mg",
      boxSize: "10x10",
      shelf: "E10",
      price: 4,
      supplierPrice: 2.8,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 430,
      image: "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "ACE inhibitor tablet used for blood pressure control.",
      categoryId: catCardio.id,
      typeId: typeTablet.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },

    {
      name: "Pantoprazole",
      genericName: "Pantoprazole Sodium",
      strength: "20mg",
      boxSize: "10x10",
      shelf: "F2",
      price: 8,
      supplierPrice: 5.5,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 700,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Gastric acid control tablet.",
      categoryId: catGastro.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Esomeprazole",
      genericName: "Esomeprazole Magnesium",
      strength: "20mg",
      boxSize: "10x10",
      shelf: "F3",
      price: 12,
      supplierPrice: 8.5,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 520,
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Capsule used for gastric acid and reflux control.",
      categoryId: catGastro.id,
      typeId: typeCapsule.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Rabeprazole",
      genericName: "Rabeprazole Sodium",
      strength: "20mg",
      boxSize: "10x10",
      shelf: "F4",
      price: 10,
      supplierPrice: 7,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 480,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Gastric acid control tablet.",
      categoryId: catGastro.id,
      typeId: typeTablet.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Domperidone",
      genericName: "Domperidone Maleate",
      strength: "10mg",
      boxSize: "10x10",
      shelf: "F5",
      price: 3.5,
      supplierPrice: 2.4,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 650,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Medicine used for nausea and gastric motility support.",
      categoryId: catGastro.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Ondansetron",
      genericName: "Ondansetron HCl",
      strength: "8mg",
      boxSize: "10x10",
      shelf: "F6",
      price: 15,
      supplierPrice: 10.5,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 300,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Anti-nausea tablet used for vomiting control.",
      categoryId: catGastro.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Loperamide",
      genericName: "Loperamide HCl",
      strength: "2mg",
      boxSize: "10x10",
      shelf: "F7",
      price: 3,
      supplierPrice: 2,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 420,
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Capsule used for diarrhea control.",
      categoryId: catGastro.id,
      typeId: typeCapsule.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "ORS Saline",
      genericName: "Oral Rehydration Salts",
      strength: "500ml",
      boxSize: "20 sachets",
      shelf: "F8",
      price: 6,
      supplierPrice: 4,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 900,
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Oral rehydration salt for dehydration support.",
      categoryId: catGastro.id,
      typeId: typeSyrup.id,
      supplierId: supBeximco.id,
      unitId: unitMl.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Antacid Suspension",
      genericName: "Aluminium Hydroxide + Magnesium Hydroxide",
      strength: "200ml",
      boxSize: "1 bottle",
      shelf: "F9",
      price: 95,
      supplierPrice: 70,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 150,
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Liquid antacid preparation for acidity relief.",
      categoryId: catGastro.id,
      typeId: typeSyrup.id,
      supplierId: supOrion.id,
      unitId: unitMl.id,
      leafSettingId: leafStd.id,
    },

    {
      name: "Napa",
      genericName: "Paracetamol",
      strength: "500mg",
      boxSize: "10x10",
      shelf: "G1",
      price: 1.5,
      supplierPrice: 1,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 1200,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Popular fever and pain relief tablet in Bangladesh.",
      categoryId: catAnalgesics.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Napa Extra",
      genericName: "Paracetamol + Caffeine",
      strength: "500mg + 65mg",
      boxSize: "10x10",
      shelf: "G2",
      price: 2.5,
      supplierPrice: 1.8,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 900,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Combination pain relief tablet with caffeine.",
      categoryId: catAnalgesics.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Ace",
      genericName: "Paracetamol",
      strength: "500mg",
      boxSize: "10x10",
      shelf: "G3",
      price: 1.5,
      supplierPrice: 1,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 1100,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Paracetamol tablet used for fever and pain relief.",
      categoryId: catAnalgesics.id,
      typeId: typeTablet.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Fast",
      genericName: "Paracetamol",
      strength: "500mg",
      boxSize: "10x10",
      shelf: "G4",
      price: 1.5,
      supplierPrice: 1,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 950,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Paracetamol tablet for fever and pain relief.",
      categoryId: catAnalgesics.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Reset",
      genericName: "Paracetamol",
      strength: "500mg",
      boxSize: "10x10",
      shelf: "G5",
      price: 1.5,
      supplierPrice: 1,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 1000,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Fever and pain relief tablet commonly used in Bangladesh.",
      categoryId: catAnalgesics.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },

    {
      name: "Seclo",
      genericName: "Omeprazole",
      strength: "20mg",
      boxSize: "10x10",
      shelf: "H1",
      price: 5,
      supplierPrice: 3.5,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 850,
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Common gastric capsule used for acidity and reflux.",
      categoryId: catGastro.id,
      typeId: typeCapsule.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Losectil",
      genericName: "Omeprazole",
      strength: "20mg",
      boxSize: "10x10",
      shelf: "H2",
      price: 5,
      supplierPrice: 3.6,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 700,
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Omeprazole capsule for gastric acid control.",
      categoryId: catGastro.id,
      typeId: typeCapsule.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "DP",
      genericName: "Domperidone",
      strength: "10mg",
      boxSize: "10x10",
      shelf: "H3",
      price: 2,
      supplierPrice: 1.3,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 800,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Medicine used for nausea, vomiting, and gastric motility support.",
      categoryId: catGastro.id,
      typeId: typeTablet.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Motigut",
      genericName: "Domperidone",
      strength: "10mg",
      boxSize: "10x10",
      shelf: "H4",
      price: 2,
      supplierPrice: 1.3,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 720,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Domperidone tablet for nausea and gastric motility support.",
      categoryId: catGastro.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Maxpro",
      genericName: "Esomeprazole Magnesium",
      strength: "20mg",
      boxSize: "10x10",
      shelf: "H5",
      price: 7,
      supplierPrice: 5,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 650,
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Esomeprazole capsule for acidity and gastric reflux.",
      categoryId: catGastro.id,
      typeId: typeCapsule.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Pantonix",
      genericName: "Pantoprazole Sodium",
      strength: "20mg",
      boxSize: "10x10",
      shelf: "H6",
      price: 6,
      supplierPrice: 4.2,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 600,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Pantoprazole tablet for gastric acid control.",
      categoryId: catGastro.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "DP Suspension",
      genericName: "Domperidone",
      strength: "5mg/5ml",
      boxSize: "1 bottle",
      shelf: "H7",
      price: 35,
      supplierPrice: 25,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 180,
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Domperidone suspension for nausea and vomiting support.",
      categoryId: catGastro.id,
      typeId: typeSyrup.id,
      supplierId: supSquare.id,
      unitId: unitMl.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Antacid Plus",
      genericName: "Aluminium Hydroxide + Magnesium Hydroxide + Simethicone",
      strength: "200ml",
      boxSize: "1 bottle",
      shelf: "H8",
      price: 90,
      supplierPrice: 65,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 160,
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Liquid antacid preparation for acidity and gas relief.",
      categoryId: catGastro.id,
      typeId: typeSyrup.id,
      supplierId: supBeximco.id,
      unitId: unitMl.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Orsaline-N",
      genericName: "Oral Rehydration Salts",
      strength: "20.5g sachet",
      boxSize: "20 sachets",
      shelf: "H9",
      price: 6,
      supplierPrice: 4,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 1500,
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "ORS sachet for dehydration and fluid replacement.",
      categoryId: catGastro.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "SMC ORS",
      genericName: "Oral Rehydration Salts",
      strength: "20.5g sachet",
      boxSize: "20 sachets",
      shelf: "H10",
      price: 6,
      supplierPrice: 4,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 1300,
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Oral rehydration salt commonly used for dehydration support.",
      categoryId: catGastro.id,
      typeId: typeTablet.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },

    {
      name: "Monas",
      genericName: "Montelukast Sodium",
      strength: "10mg",
      boxSize: "10x10",
      shelf: "I1",
      price: 15,
      supplierPrice: 10.5,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 520,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Tablet used for allergy and respiratory symptom support.",
      categoryId: catGastro.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "DPH",
      genericName: "Diphenhydramine",
      strength: "10mg/5ml",
      boxSize: "1 bottle",
      shelf: "I2",
      price: 55,
      supplierPrice: 38,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 190,
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Syrup used for allergy and cough symptom relief.",
      categoryId: catAnalgesics.id,
      typeId: typeSyrup.id,
      supplierId: supSquare.id,
      unitId: unitMl.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Tusca Plus",
      genericName: "Dextromethorphan + Phenylephrine + Triprolidine",
      strength: "100ml",
      boxSize: "1 bottle",
      shelf: "I3",
      price: 80,
      supplierPrice: 58,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 210,
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Cough and cold syrup for symptomatic relief.",
      categoryId: catGastro.id,
      typeId: typeSyrup.id,
      supplierId: supBeximco.id,
      unitId: unitMl.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Salbutal",
      genericName: "Salbutamol",
      strength: "4mg",
      boxSize: "10x10",
      shelf: "I4",
      price: 1.5,
      supplierPrice: 1,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 700,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Respiratory support tablet used for breathing-related symptoms.",
      categoryId: catGastro.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Sultolin",
      genericName: "Salbutamol",
      strength: "100mcg/puff",
      boxSize: "1 inhaler",
      shelf: "I5",
      price: 220,
      supplierPrice: 170,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 85,
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Respiratory inhaler used for breathing support.",
      categoryId: catGastro.id,
      typeId: typeSyrup.id,
      supplierId: supOrion.id,
      unitId: unitMl.id,
      leafSettingId: leafStd.id,
    },

    {
      name: "Fexo",
      genericName: "Fexofenadine HCl",
      strength: "120mg",
      boxSize: "10x10",
      shelf: "J1",
      price: 8,
      supplierPrice: 5.6,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 620,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Antihistamine tablet used for allergy symptoms.",
      categoryId: catAnalgesics.id,
      typeId: typeTablet.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Fenadin",
      genericName: "Fexofenadine HCl",
      strength: "120mg",
      boxSize: "10x10",
      shelf: "J2",
      price: 8,
      supplierPrice: 5.6,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 560,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Allergy relief tablet.",
      categoryId: catAnalgesics.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Alatrol",
      genericName: "Cetirizine HCl",
      strength: "10mg",
      boxSize: "10x10",
      shelf: "J3",
      price: 3,
      supplierPrice: 2,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 900,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Cetirizine tablet used for allergy symptoms.",
      categoryId: catAnalgesics.id,
      typeId: typeTablet.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "DP Cetirizine",
      genericName: "Cetirizine HCl",
      strength: "5mg/5ml",
      boxSize: "1 bottle",
      shelf: "J4",
      price: 35,
      supplierPrice: 24,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 200,
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Cetirizine syrup for allergy symptom support.",
      categoryId: catAnalgesics.id,
      typeId: typeSyrup.id,
      supplierId: supBeximco.id,
      unitId: unitMl.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Lora",
      genericName: "Loratadine",
      strength: "10mg",
      boxSize: "10x10",
      shelf: "J5",
      price: 4,
      supplierPrice: 2.8,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 600,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Loratadine tablet used for allergy relief.",
      categoryId: catAnalgesics.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },

    {
      name: "Fluconazole",
      genericName: "Fluconazole",
      strength: "150mg",
      boxSize: "1x10",
      shelf: "K1",
      price: 22,
      supplierPrice: 16,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 210,
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Antifungal capsule used for fungal infections.",
      categoryId: catAntibiotics.id,
      typeId: typeCapsule.id,
      supplierId: supSquare.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Albendazole",
      genericName: "Albendazole",
      strength: "400mg",
      boxSize: "10x10",
      shelf: "K2",
      price: 6,
      supplierPrice: 4.2,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 600,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Anthelmintic tablet used for worm infection treatment.",
      categoryId: catGastro.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Mebendazole",
      genericName: "Mebendazole",
      strength: "100mg",
      boxSize: "10x10",
      shelf: "K3",
      price: 4,
      supplierPrice: 2.8,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 450,
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Anthelmintic tablet used for worm infection treatment.",
      categoryId: catGastro.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Insulin Regular",
      genericName: "Human Insulin",
      strength: "100IU/ml",
      boxSize: "1 vial",
      shelf: "K4",
      price: 420,
      supplierPrice: 350,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 90,
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Regular insulin preparation for diabetes management.",
      categoryId: catCardio.id,
      typeId: typeSyrup.id,
      supplierId: supSquare.id,
      unitId: unitMl.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Gliclazide",
      genericName: "Gliclazide",
      strength: "80mg",
      boxSize: "10x10",
      shelf: "K5",
      price: 5,
      supplierPrice: 3.5,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 500,
      image: "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Diabetes care tablet used for blood sugar control.",
      categoryId: catCardio.id,
      typeId: typeTablet.id,
      supplierId: supBeximco.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
    {
      name: "Glimepiride",
      genericName: "Glimepiride",
      strength: "2mg",
      boxSize: "10x10",
      shelf: "K6",
      price: 6.5,
      supplierPrice: 4.5,
      vat: 0,
      expiryDate: new Date("2027-06-30"),
      stockQuantity: 460,
      image: "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=900&auto=format&fit=crop&q=80",
      imagePublicId: null,
      description: "Diabetes care tablet used for blood sugar control.",
      categoryId: catCardio.id,
      typeId: typeTablet.id,
      supplierId: supOrion.id,
      unitId: unitMg.id,
      leafSettingId: leafStd.id,
    },
  ];

  const medicines = await Promise.all(
    medicineData.map(async (m) => {
      const existing = await prisma.medicine.findFirst({
        where: { name: m.name },
      });

      if (existing) {
        return prisma.medicine.update({
          where: { id: existing.id },
          data: {
            ...m,
          },
        });
      }

      return prisma.medicine.create({
        data: {
          ...m,
        },
      });
    })
  );

  // ── 4. Pharmacies ─────────────────────────────────────────────────────────────
  console.log("  → Pharmacies");

  // Approved pharmacy (linked to pharmacyUser)
  let approvedPharmacy = await prisma.pharmacy.findUnique({ where: { ownerId: pharmacyUser.id } });
  if (!approvedPharmacy) {
    approvedPharmacy = await prisma.pharmacy.create({
      data: {
        ownerId: pharmacyUser.id,
        name: "MediTrack Demo Pharmacy",
        licenseNumber: "LIC-2024-DEMO-001",
        binVat: "BIN-123456",
        pharmacyType: "RETAIL",
        establishedYear: 2018,
        staffCount: 5,
        openingHours: "8:00 AM – 10:00 PM",
        website: "https://demo-pharmacy.meditrack.com",
        phone: "01711111111",
        address: "House 12, Road 5, Rangpur Sadar, Rangpur",
        status: "APPROVED",
        inviteCode: "DEMO-STAFF-2024",
      },
    });
  }

  // Pending pharmacy
  const pendingOwnerEmail = envConfig.PENDING_OWNER_EMAIL;
  let pendingOwner = await prisma.user.findUnique({ where: { email: pendingOwnerEmail } });
  if (!pendingOwner) {
    pendingOwner = await upsertUser("Pending Pharmacy Owner", pendingOwnerEmail,envConfig.PHARMACY_Password, "PHARMACY");
  }
  await prisma.pharmacy.upsert({
    where: { ownerId: pendingOwner.id },
    update: {},
    create: {
      ownerId: pendingOwner.id, name: "New Care Pharmacy", licenseNumber: "LIC-2024-PEND-002",
      pharmacyType: "RETAIL", phone: "01722222222", address: "Rangpur City Corporation, Rangpur",
      status: "PENDING",
    },
  });

  // Rejected pharmacy
  const rejectedOwnerEmail = envConfig.REJECTED_OWNER_EMAIL;
  let rejectedOwner = await prisma.user.findUnique({ where: { email: rejectedOwnerEmail } });
  if (!rejectedOwner) {
    rejectedOwner = await upsertUser("Rejected Owner", rejectedOwnerEmail,envConfig.PHARMACY_Password, "PHARMACY");
  }
  await prisma.pharmacy.upsert({
    where: { ownerId: rejectedOwner.id },
    update: {},
    create: {
      ownerId: rejectedOwner.id, name: "Quick Meds Store", licenseNumber: "LIC-2024-REJ-003",
      pharmacyType: "WHOLESALE", phone: "01733333333", address: "Dinajpur Road, Rangpur",
      status: "REJECTED", rejectionReason: "Incomplete documentation submitted. Please resubmit with valid license.",
    },
  });

  // ── 5. Staff ─────────────────────────────────────────────────────────────────
  console.log("  → Staff");

  const staffEmail = "staff@meditrack.com";
  let staffUser = await prisma.user.findUnique({ where: { email: staffEmail } });
  if (!staffUser) {
    staffUser = await upsertUser("Demo Staff", staffEmail, envConfig.STAFF_Password, "STAFF", "DEMO-STAFF-2024");
  }
  await prisma.staff.upsert({
    where: { userId: staffUser.id },
    update: {},
    create: {
      userId: staffUser.id,
      pharmacyId: approvedPharmacy.id,
      canManageInventory: true,
      canManageSales: true,
      canManageCustomers: true,
      canViewReports: true,
      canManagePurchases: false,
    },
  });

  // ── 6. Inventory ─────────────────────────────────────────────────────────────
  console.log("  → Inventory");

  // Helper: upsert inventory for the approved pharmacy
  async function upsertInventory(
    medicineIdx: number,
    stock: number,
    sellingPrice: number,
    purchasePrice: number,
    lowStockAlert = 20,
    expiryOverride?: Date
  ) {
    const medicine = medicines[medicineIdx];
    if (!medicine) return null;
    const existing = await prisma.pharmacyInventory.findFirst({
      where: { pharmacyId: approvedPharmacy!.id, medicineId: medicine.id },
    });
    if (existing) {
      return prisma.pharmacyInventory.update({
        where: { id: existing.id },
        data: {
          stockQuantity: stock,
          sellingPrice,
          purchasePrice,
          ...(expiryOverride ? { expiryDate: expiryOverride } : {}),
        },
      });
    }
    return prisma.pharmacyInventory.create({
      data: {
        pharmacyId: approvedPharmacy!.id,
        medicineId: medicine.id,
        stockQuantity: stock,
        sellingPrice: dec(sellingPrice),
        purchasePrice: dec(purchasePrice),
        lowStockAlertQuantity: lowStockAlert,
        expiryDate: expiryOverride ?? new Date("2027-06-30"),
        batchNumber: `BATCH-${medicine.id.slice(0, 6).toUpperCase()}`,
        shelf: `A${medicineIdx + 1}`,
      },
    });
  }

  const inv0 = await upsertInventory(0, 200, 15.00, 9.00);   // Amoxicillin — normal
  const inv1 = await upsertInventory(1, 500, 6.00, 3.50);   // Paracetamol — normal
  const inv2 = await upsertInventory(2, 80, 40.00, 25.00);  // Napa Syrup — normal
  const inv3 = await upsertInventory(3, 5, 50.00, 30.00, 20); // Azithromycin — LOW STOCK
  const inv4 = await upsertInventory(4, 60, 130.00, 90.00, 10, new Date(Date.now() + 15 * 24 * 60 * 60 * 1000)); // Oseltamivir — EXPIRING SOON
  const inv5 = await upsertInventory(5, 300, 10.00, 5.00);   // Vitamin C
  const inv6 = await upsertInventory(6, 150, 22.00, 12.00);  // Atorvastatin
  const inv7 = await upsertInventory(7, 250, 12.00, 7.00);   // Omeprazole

  // ── 7. Customers ─────────────────────────────────────────────────────────────
  console.log("  → Customers");

  const [cust1, cust2, cust3] = await Promise.all([
    prisma.customer.upsert({
      where: { id: "cust-seed-001" },
      update: {},
      create: { id: "cust-seed-001", pharmacyId: approvedPharmacy.id, name: "Md. Rahman Hossain", phone: "01811111111", email: "rahman@example.com", address: "Rangpur Sadar, Rangpur" },
    }),
    prisma.customer.upsert({
      where: { id: "cust-seed-002" },
      update: {},
      create: { id: "cust-seed-002", pharmacyId: approvedPharmacy.id, name: "Fatema Khatun", phone: "01822222222", email: "fatema@example.com", address: "Dinajpur Road, Rangpur" },
    }),
    prisma.customer.upsert({
      where: { id: "cust-seed-003" },
      update: {},
      create: { id: "cust-seed-003", pharmacyId: approvedPharmacy.id, name: "Karim Uddin", phone: "01833333333", email: "karim@example.com", address: "Parbatipur, Rangpur" },
    }),
  ]);

  // ── 8. Purchases ─────────────────────────────────────────────────────────────
  console.log("  → Purchases");

  // Purchase 1 — RECEIVED (stock already updated)
  const pur1 = await prisma.purchase.upsert({
    where: { pharmacyId_invoiceNumber: { pharmacyId: approvedPharmacy.id, invoiceNumber: "PUR-SEED-001" } },
    update: {},
    create: {
      pharmacyId: approvedPharmacy.id,
      supplierId: supSquare.id,
      invoiceNumber: "PUR-SEED-001",
      purchaseDate: new Date("2026-04-15"),
      subtotal: dec(1800),
      vatAmount: dec(0),
      discount: dec(0),
      totalAmount: dec(1800),
      paidAmount: dec(1800),
      dueAmount: dec(0),
      paymentStatus: "PAID",
      purchaseStatus: "RECEIVED",
      note: "Demo received purchase — stock already credited",
      createdByUserId: pharmacyUser.id,
      items: {
        create: [
          { medicineId: medicines[0]!.id, inventoryId: inv0?.id ?? null, quantity: 100, purchasePrice: dec(9.00), sellingPrice: dec(15.00), total: dec(900), batchNumber: "BAT-001A", expiryDate: new Date("2027-06-30") },
          { medicineId: medicines[1]!.id, inventoryId: inv1?.id ?? null, quantity: 200, purchasePrice: dec(3.50), sellingPrice: dec(6.00), total: dec(700), batchNumber: "BAT-001B", expiryDate: new Date("2027-06-30") },
          { medicineId: medicines[5]!.id, inventoryId: inv5?.id ?? null, quantity: 100, purchasePrice: dec(5.00), sellingPrice: dec(10.00), total: dec(500), batchNumber: "BAT-001C", expiryDate: new Date("2027-06-30") },
        ],
      },
    },
  });

  // Purchase 2 — PENDING (stock not yet credited)
  await prisma.purchase.upsert({
    where: { pharmacyId_invoiceNumber: { pharmacyId: approvedPharmacy.id, invoiceNumber: "PUR-SEED-002" } },
    update: {},
    create: {
      pharmacyId: approvedPharmacy.id,
      supplierId: supOrion.id,
      invoiceNumber: "PUR-SEED-002",
      purchaseDate: new Date("2026-05-01"),
      subtotal: dec(1200),
      vatAmount: dec(0),
      discount: dec(0),
      totalAmount: dec(1200),
      paidAmount: dec(500),
      dueAmount: dec(700),
      paymentStatus: "PARTIAL",
      purchaseStatus: "PENDING",
      note: "Demo pending purchase — awaiting delivery",
      createdByUserId: pharmacyUser.id,
      items: {
        create: [
          { medicineId: medicines[2]!.id, inventoryId: inv2?.id ?? null, quantity: 30, purchasePrice: dec(25.00), sellingPrice: dec(40.00), total: dec(750), batchNumber: "BAT-002A", expiryDate: new Date("2027-12-31") },
          { medicineId: medicines[7]!.id, inventoryId: inv7?.id ?? null, quantity: 50, purchasePrice: dec(9.00), sellingPrice: dec(15.00), total: dec(450), batchNumber: "BAT-002B", expiryDate: new Date("2027-12-31") },
        ],
      },
    },
  });

  // ── 9. Invoices + Payments ────────────────────────────────────────────────────
  console.log("  → Invoices & Payments");

  // Invoice 1 — UNPAID
  await prisma.invoice.upsert({
    where: { pharmacyId_invoiceNumber: { pharmacyId: approvedPharmacy.id, invoiceNumber: "INV-SEED-001" } },
    update: {},
    create: {
      pharmacyId: approvedPharmacy.id,
      customerId: cust1.id,
      invoiceNumber: "INV-SEED-001",
      saleDate: new Date("2026-05-01"),
      subtotal: dec(180),
      vatAmount: dec(0),
      discount: dec(0),
      totalAmount: dec(180),
      netAmount: dec(180),
      paidAmount: dec(0),
      dueAmount: dec(180),
      paymentMode: "CASH",
      paymentStatus: "UNPAID",
      status: "ISSUED",
      note: "Demo unpaid invoice",
      createdByUserId: pharmacyUser.id,
      items: {
        create: [
          { medicineId: medicines[0]!.id, inventoryId: inv0?.id ?? null, quantity: 10, unitPrice: dec(15.00), vat: dec(0), discount: dec(0), total: dec(150) },
          { medicineId: medicines[5]!.id, inventoryId: inv5?.id ?? null, quantity: 3, unitPrice: dec(10.00), vat: dec(0), discount: dec(0), total: dec(30) },
        ],
      },
    },
  });

  // Invoice 2 — PARTIAL (60% paid)
  const inv2seed = await prisma.invoice.upsert({
    where: { pharmacyId_invoiceNumber: { pharmacyId: approvedPharmacy.id, invoiceNumber: "INV-SEED-002" } },
    update: {},
    create: {
      pharmacyId: approvedPharmacy.id,
      customerId: cust2.id,
      invoiceNumber: "INV-SEED-002",
      saleDate: new Date("2026-05-02"),
      subtotal: dec(300),
      vatAmount: dec(0),
      discount: dec(0),
      totalAmount: dec(300),
      netAmount: dec(300),
      paidAmount: dec(180),
      dueAmount: dec(120),
      paymentMode: "CASH",
      paymentStatus: "PARTIAL",
      status: "ISSUED",
      note: "Demo partial payment invoice",
      createdByUserId: pharmacyUser.id,
      items: {
        create: [
          { medicineId: medicines[6]!.id, inventoryId: inv6?.id ?? null, quantity: 5, unitPrice: dec(22.00), vat: dec(0), discount: dec(0), total: dec(110) },
          { medicineId: medicines[7]!.id, inventoryId: inv7?.id ?? null, quantity: 5, unitPrice: dec(12.00), vat: dec(0), discount: dec(0), total: dec(60) },
          { medicineId: medicines[1]!.id, inventoryId: inv1?.id ?? null, quantity: 10, unitPrice: dec(6.00), vat: dec(0), discount: dec(0), total: dec(60) },
          { medicineId: medicines[0]!.id, inventoryId: inv0?.id ?? null, quantity: 3, unitPrice: dec(15.00), vat: dec(0), discount: dec(15), total: dec(30) },
        ],
      },
    },
  });

  // Payment for Invoice 2 (partial)
  const existingPay2 = await prisma.payment.findFirst({ where: { invoiceId: inv2seed.id } });
  if (!existingPay2) {
    await prisma.payment.create({
      data: {
        invoiceId: inv2seed.id,
        pharmacyId: approvedPharmacy.id,
        amount: dec(180),
        paymentMode: "CASH",
        paymentDate: new Date("2026-05-02"),
        note: "Initial partial payment",
        receivedByUserId: pharmacyUser.id,
      },
    });
  }

  // Invoice 3 — PAID
  const inv3seed = await prisma.invoice.upsert({
    where: { pharmacyId_invoiceNumber: { pharmacyId: approvedPharmacy.id, invoiceNumber: "INV-SEED-003" } },
    update: {},
    create: {
      pharmacyId: approvedPharmacy.id,
      customerId: cust3.id,
      invoiceNumber: "INV-SEED-003",
      saleDate: new Date("2026-04-28"),
      subtotal: dec(250),
      vatAmount: dec(0),
      discount: dec(0),
      totalAmount: dec(250),
      netAmount: dec(250),
      paidAmount: dec(250),
      dueAmount: dec(0),
      paymentMode: "MOBILE_BANKING",
      paymentStatus: "PAID",
      status: "PAID",
      note: "Demo fully paid invoice",
      createdByUserId: pharmacyUser.id,
      items: {
        create: [
          { medicineId: medicines[4]!.id, inventoryId: inv4?.id ?? null, quantity: 1, unitPrice: dec(130.00), vat: dec(0), discount: dec(0), total: dec(130) },
          { medicineId: medicines[3]!.id, inventoryId: inv3?.id ?? null, quantity: 2, unitPrice: dec(50.00), vat: dec(0), discount: dec(0), total: dec(100) },
          { medicineId: medicines[5]!.id, inventoryId: inv5?.id ?? null, quantity: 2, unitPrice: dec(10.00), vat: dec(0), discount: dec(0), total: dec(20) },
        ],
      },
    },
  });

  // Payment for Invoice 3 (full)
  const existingPay3 = await prisma.payment.findFirst({ where: { invoiceId: inv3seed.id } });
  if (!existingPay3) {
    await prisma.payment.create({
      data: {
        invoiceId: inv3seed.id,
        pharmacyId: approvedPharmacy.id,
        amount: dec(250),
        paymentMode: "MOBILE_BANKING",
        paymentDate: new Date("2026-04-28"),
        note: "Full payment via bKash",
        receivedByUserId: pharmacyUser.id,
      },
    });
  }

  // ─────────────────────────────────────────────────────────────────────────────
  console.log("\n✅ Seeding complete!\n");
  console.log("══════════════════════════════════════════════════");
  console.log("  DEMO CREDENTIALS");
  console.log("══════════════════════════════════════════════════");
  console.log(`  Admin    → ${envConfig.ADMIN_Email}`);
  console.log(`  Pharmacy → ${envConfig.PHARMACY_Email}`);
  console.log(`  Staff    → ${envConfig.STAFF_Email} `);
  console.log(`  User     → ${envConfig.USER_Email} `);
  console.log("══════════════════════════════════════════════════\n");
}

main()
  .catch((err) => {
    console.error("❌ Seed failed:", err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());